create table px_projects (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , name_jtl      json          not null
  , alias         varchar2(32)
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint px_projects_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/
comment on column px_projects.name_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
create or replace trigger px_projects_u
before update
on px_projects
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
insert into PX_PROJECTS (NAME_JTL,ALIAS,ACTIVE_IND) values ('[{"l":"en","tl":"Gardening"},{"l":"fr","tl":"Gardening - Français"},{"l":"es","tl":"Sembrar"}]','Garden','Y');
insert into PX_PROJECTS (NAME_JTL,ALIAS,ACTIVE_IND) values ('[{"l":"en","tl":"Painting"},{"l":"fr","tl":"Painting - Français"},{"l":"es","tl":"Pintar"}]','Paint 2','Y');

create or replace view px_projects_vl
as
select t.id
     , t.name_jtl
     , jd.lang
     , jd.tl name
     , t.alias
     , t.active_ind
     , t.created_by
     , t.created_on
     , t.updated_by
     , t.updated_on
  from px_projects t
     , json_table(t.name_jtl, '$[*]'
        columns (
             lang varchar2(10)      path '$.l'
           , tl   varchar2(60 char) path '$.tl'
       )) jd
 where jd.lang = (select nvl(apex_util.get_session_lang,'en') from dual)
/

create table px_projects2 (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , name_jtl      json          not null
  , description_jtl json        not null
  , alias         varchar2(32)
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint px_projects2_ck_active check (active_ind in ('Y', 'N'))
)
enable primary key using index
/
comment on column px_projects2.name_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
comment on column px_projects2.description_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
create or replace trigger px_projects2_u
before update
on px_projects2
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
insert into PX_PROJECTS2 (NAME_JTL,DESCRIPTION_JTL,ALIAS,ACTIVE_IND) values ('[{"l":"en","tl":"Name 1 - English"},{"l":"fr","tl":"Nom 1 - Français"},{"l":"es","tl":"Nombre 1 - Español"}]','[{"l":"en","tl":"Desc 1 - English"},{"l":"fr","tl":"Desc 1 - Français"},{"l":"es","tl":"Desc 1 - Español"}]','Nom 1','Y');
insert into PX_PROJECTS2 (NAME_JTL,DESCRIPTION_JTL,ALIAS,ACTIVE_IND) values ('[{"l":"en","tl":"Nom 2- English"},{"l":"fr","tl":"Nom 2 - Français"},{"l":"es","tl":"Nom 2 - Español"}]','[{"l":"en","tl":"Desc 2 - English"},{"l":"fr","tl":"Desc 2 - Français"},{"l":"es","tl":"Desc 2 - Español"}]','Nom 2','Y');

create or replace view px_projects2_vl
as
with n_tl as (
  select /*+ no_merge */ p.id
       , t.lang
       , t.tl
    from px_projects2 p
       , json_table(p.name_jtl, '$[*]'
          columns (
                   lang varchar2(10) path '$.l'
                 , tl   varchar2(50 char) path '$.tl'
                  )
        ) t
),
d_tl as (
  select /*+ no_merge */ p.id
       , t.lang
       , t.tl
    from px_projects2 p
       , json_table(p.description_jtl, '$[*]'
          columns (
                   lang varchar2(10) path '$.l'
                 , tl   varchar2(1000 char) path '$.tl'
                  )
        ) t
)
select p.id
     , p.name_jtl
     , p.description_jtl
     , n_tl.lang
     , n_tl.tl   name
     , d_tl.tl   description
     , p.alias
     , p.active_ind
     , p.created_by
     , p.created_on
     , p.updated_by
     , p.updated_on
  from px_projects2 p
     , n_tl
     , d_tl
 where p.id = n_tl.id
   and p.id = d_tl.id
   and n_tl.lang = d_tl.lang
   and n_tl.lang = (select nvl(apex_util.get_session_lang,'en') from dual)
/

create table px_jtl_with_clob (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , name_jtl      varchar2(500)   not null constraint px_jtl_with_clob_name_tl_ck CHECK (name_jtl is json(strict))
  , description_jtl clob not null constraint px_jtl_with_clob_desc_tl_ck CHECK (description_jtl is json(strict))
  , alias         varchar2(32)
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint px_jtl_with_clob_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/
comment on table px_jtl_with_clob is 'Demo table to test clobs';
comment on column px_jtl_with_clob.name_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
comment on column px_jtl_with_clob.description_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
create or replace trigger px_jtl_with_clob_u
before update
on px_jtl_with_clob
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
create or replace view px_jtl_with_clob_vl
as
with n_tl as (
  select /*+ no_merge */ p.id
       , t.lang
       , t.tl
    from px_jtl_with_clob p
       , json_table(p.name_jtl, '$[*]'
          columns (
                   lang varchar2(10) path '$.l'
                 , tl   varchar2(50 char) path '$.tl'
                  )
        ) t
),
d_tl as (
  select /*+ no_merge */ p.id
       , t.lang
       , t.tl
    from px_jtl_with_clob p
       , json_table(p.description_jtl, '$[*]'
          columns (
                   lang varchar2(10) path '$.l'
                 , tl   varchar2(4000) path '$.tl'
                  )
        ) t
)
select p.id
     , p.name_jtl
     , p.description_jtl
     , n_tl.lang
     , n_tl.tl   name
     , d_tl.tl   description
     , p.alias
     , p.active_ind
     , p.created_by
     , p.created_on
     , p.updated_by
     , p.updated_on
  from px_jtl_with_clob p
     , n_tl
     , d_tl
 where p.id = n_tl.id
   and p.id = d_tl.id
   and n_tl.lang = d_tl.lang
   and n_tl.lang = (select nvl(apex_util.get_session_lang,'en') from dual)
/

create table px_projects_json (
    id            number generated by default on null as identity primary key not null
  , name_jtl      json
  , alias         varchar2(32)
  , active_ind    varchar2(1) default 'Y' not null
  , constraint px_projects_json_ck_active check (active_ind in ('Y','N'))
)
/
create or replace view px_projects_json_vl
as
select t.id
     , t.name_jtl
     , jd.lang
     , jd.tl name
     , t.alias
     , t.active_ind
  from px_projects_json t
     , json_table(t.name_jtl, '$[*]'
        columns (
             lang varchar2(10)      path '$.l'
           , tl   varchar2(60 char) path '$.tl'
       )) jd
 where jd.lang = (select nvl(apex_util.get_session_lang,'en') from dual)
/
insert into px_projects_json (name_jtl, alias, active_ind) values ('[{"l":"en","tl":"JSON Form Seed"},{"l":"fr","tl":"Forme JSON"},{"l":"es","tl":"Formulario JSON"}]','json1','Y');
