-- Native JSON datatype variant of the px_projects demo table (Oracle 21c/23ai+).
-- The JSON type needs no IS JSON constraint (validity is inherent), has no
-- 32k byte ceiling under multi-byte character sets, and json_table reads it
-- unchanged. See README "Native JSON Columns" for the APEX support matrix.
create table px_projects_json (
    id            number generated by default on null as identity primary key not null
  , name_jtl      json
  , alias         varchar2(32)
  , active_ind    varchar2(1) default 'Y' not null
  , constraint px_projects_json_ck_active check (active_ind in ('Y','N'))
)
/

create or replace view px_projects_json_vl
as
select t.id
     , t.name_jtl
     , jd.lang
     , jd.tl name
     , t.alias
     , t.active_ind
  from px_projects_json t
     , json_table(t.name_jtl, '$[*]'
        columns (
             lang varchar2(10)      path '$.l'
           , tl   varchar2(60 char) path '$.tl'
       )) jd
 where jd.lang = (select nvl(apex_util.get_session_lang,'en') from dual)
/

insert into px_projects_json (name_jtl, alias, active_ind) values (
  '[{"l":"en","tl":"JSON Form Seed"},{"l":"fr","tl":"Forme JSON"},{"l":"es","tl":"Formulario JSON"}]'
, 'json1'
, 'Y'
);

